# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_lacunarity <- function(mat, r_vec, fun, ncores = 1L, display_progress = FALSE) {
    .Call(`_CGEI_rcpp_lacunarity`, mat, r_vec, fun, ncores, display_progress)
}

